services:
  webapp:
    stdin_open: true
    tty: true
    build:
      dockerfile: ./ruby/Dockerfile
      context: ./
    ports:
      - "1323:1323"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    command: bundle exec unicorn -c unicorn.conf.rb
    depends_on:
      - mysql
    volumes:
      - ./fixture:/webapp/fixture
      - ./ruby:/webapp/ruby
      - ./mysql/db:/webapp/mysql/db
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"
  # nginx:
  #   image: nginx:1.17
  #   volumes:
  #     - ./frontend/out:/www/data
  #     - ./nginx:/etc/nginx/conf.d/
  #   ports:
  #     - "127.0.0.1:1323:80"
